# random overlay farmer: easter eggs de nombre ocultan el clothing (skin 3 transp.); resto VR(1)/A&S(2)
skins.1=3
names.1=villager32 Villager32 hoppity Hoppity bunny Bunny elf Elf ghost Ghost boo Boo
skins.2=1 2
