# fox.properties — selección de modelo CEM (EMF). Generado por tools/build_fox.py.
# Baby ártico (bioma frío) antes que baby rojo; el adulto cae al fox.jem por defecto
# (su variante roja/ártica la resuelve el juego por ResourceLocation vanilla).
models.1=3
baby.1=true
biomes.1=minecraft:snowy_beach minecraft:snowy_taiga minecraft:snowy_plains minecraft:ice_spikes minecraft:grove minecraft:snowy_slopes minecraft:frozen_peaks minecraft:jagged_peaks minecraft:frozen_river minecraft:frozen_ocean minecraft:deep_frozen_ocean
models.2=2
baby.2=true
