# mooshroom.properties — selección de potrillo/champiñaca bebé. Generado por tools/build_mooshroom.py.
# Modelos 2/3 son baby red nombrado/real; 4/5 son brown.
models.1=4
names.1=baby Baby mooshling Mooshling mooshy Mooshy
nbt.1.Type=brown
models.2=2
names.2=baby Baby mooshling Mooshling mooshy Mooshy
models.3=5
baby.3=true
nbt.3.Type=brown
models.4=3
baby.4=true
