# sheep.properties — selección de geometría baby dedicada. Generado por tools/build_sheep.py.
# Las reglas sheared usan el atlas baby completo; las no esquiladas separan base y wool.
models.1=4
names.1=baby Baby lamb Lamb wooly Wooly
nbt.1.Sheared=1
models.2=2
names.2=baby Baby lamb Lamb wooly Wooly
models.3=5
baby.3=true
nbt.3.Sheared=1
models.4=3
baby.4=true
