# generado por build_scheduler.py - swap de modelos: dormir (NBT SleepingX, estilo FA) + bebe (cabezon)
# EASTER EGGS de nombre (name tag) primero (mas especifico gana). Cada uno con modelo despierto y de dormir.
models.1=10
names.1=ghost Ghost boo Boo
nbt.1.SleepingX=exists:true
models.2=9
names.2=ghost Ghost boo Boo
models.3=8
names.3=elf Elf
nbt.3.SleepingX=exists:true
models.4=7
names.4=elf Elf
models.5=6
names.5=hoppity Hoppity bunny Bunny
nbt.5.SleepingX=exists:true
models.6=5
names.6=hoppity Hoppity bunny Bunny
models.7=4
nbt.7.SleepingX=exists:true
baby.7=true
models.8=2
nbt.8.SleepingX=exists:true
models.9=3
baby.9=true
