models.1=19 22
names.1=party Party pawty Pawty
models.2=20
names.2=reindeer Reindeer reindog Reindog
models.3=21
names.3=skeleton Skeleton marrow Marrow
models.4=2
baby.4=true
variant.4=pale
models.5=10
baby.5=true
variant.5=ashen
models.6=11
baby.6=true
variant.6=black
models.7=12
baby.7=true
variant.7=chestnut
models.8=13
baby.8=true
variant.8=rusty
models.9=14
baby.9=true
variant.9=snowy
models.10=15
baby.10=true
variant.10=spotted
models.11=16
baby.11=true
variant.11=striped
models.12=17
baby.12=true
variant.12=woods
models.13=2
baby.13=true
