# A&S iron golem: skins por nombre de etiqueta (ETF/OptiFine random entities)
skins.1=2
names.1=iregex:(snowy|frosty)
skins.2=3
names.2=iregex:(dapper|agent)
skins.3=4
names.3=iregex:(frankenstein|frank)
skins.4=5
names.4=iregex:(claus)
